services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: polda-php:latest
    container_name: polda-app
    volumes:
      - app_code:/var/www/html
      - laravel_storage:/var/www/html/storage
    env_file:
      - .env
    networks:
      - polda_net
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: polda-nginx
    ports:
      - "8080:80"
    volumes:
      - app_code:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - laravel_storage:/var/www/html/storage
    depends_on:
      - app
    networks:
      - polda_net
    restart: unless-stopped

networks:
  polda_net:
    driver: bridge

volumes:
  laravel_storage:
  app_code:
    driver: local